### PR TITLE
Implementation of line_cancel (and cancel all lines)

### LINKED ISSUE #15: KV17cancel all trips
KV17cancel all trips should iterate over all available lines and/or trips and broadcast that this trip is canceled. This will blank the information displays. This operation should be implemented along with KV17recover all trips.

The page that allows this behavior should be protected with extra permissions.

### LINKED ISSUE #115: Add KV17 CancelAll

### PR DESCRIPTION
**Pull request by Baasje85**
Please check the permissions in admin (on my screen I see some permissions of 'ritaanpassingen' within the 'lijn-permissions'

Fix #115
Fix #15

### CODE REVIEW

**Comment by skinkie** [comment]
I don't know if the migration should or shouldn't be in this repository. They have not been committed.

**Comment by Baasje85** [comment]
I guess it wasn't my greatest idea ever to push the NotMonitored feature for LineCancel here... but I just did :(

**Comment by Baasje85** [comment]
We are going to change the Model to fit it directly on KV17Change.

Don't merge yet.

**Comment by Baasje85** [comment]
redundant ... closing request

**Pull request closed without merging**
